# Site
repository: TamerAbdElaziz/Resume
# favicon: images/favicon.ico

# Personal info
name: Tamer Abdelaziz Abdelmegid Mohamed
title: PhD Candidate in Computer Science,National University of Singapore.
email: tamer@comp.nus.edu.sg
website: https://www.comp.nus.edu.sg/~tamer/

# Social links
#twitter_username: facespics
github_username:  TamerAbdelaziz
# dribbble_username: jekyll
facebook_username: Tamer.A.Yassen
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: tamer-abdelaziz-yassen-050b6364
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/TamerAbdelaziz.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a PhD candidate in Computer Science at School of Computing, [National University of Singapore (NUS)](https://www.comp.nus.edu.sg/). I am being supervised by Assistant Professor [Aquinas Hobor](https://scholar.google.com.sg/citations?user=-SbM8VcAAAAJ&hl=en).
  
  It's my interest to research in Programming Languages and Software Engineering, I am working in: <mark>Formal verification</mark> and <mark>Analysis of mixed-language programs </mark>
  
  Lab: PL&SE Research Lab 2 (COM2-04-04)
  
  Telephone: (+65) 82977305
  
  Address: 13 Computing Drive, Singapore 117417
  
  [Curriculum Vitae](https://www.comp.nus.edu.sg/~tamer/TamerAbdelazizCV.pdf)

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me

more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Programming Languages and Software Engineering some of my other interests are:
   - Verified Compiler
   - Type Systems and Program Analyses
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
